name: Build and Release for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Nim
      uses: iffy/install-nim@v5
      with:
        version: stable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Test
      run: |
        nimble install -y
        nimble test

    - name: Build
      run: nimble build

    - name: List Files
      run: dir

    - name: Package
      run: |
        mv ./rangeit.exe ./rangeit-windows.exe
        mkdir -p release
        cp ./rangeit-windows.exe ./release/

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: rangeit-executables
        path: ./release/
