name: Build and Release for Windows

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Nim
      run: |
        curl https://nim-lang.org/choosenim/init.sh -sSf | sh -s -- -y
        echo "C:\\Users\\runneradmin\\.nimble\\bin" >> $GITHUB_PATH

    - name: Build project
      run: nimble build

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: rangeit-windows
        path: ./rangeit.exe
