on:
    workflow_dispatch:
  
  jobs:
    tests:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v5
        with:
          version: stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: |
          nimble install -y
          nimble test
      - name: Build and Package
        run: |
          nimble build
          mv ./rangeit.exe ./rangeit-windows.exe
          mkdir -p release
          cp ./rangeit-windows.exe ./release/
        env:
          RUNNER_OS: windows
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: rangeit-executables
          path: ./release/
  