name: Build and Release for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Nim
      uses: iffy/install-nim@v5
      with:
        version: stable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Test
      run: |
        nimble install -y
        nimble test

    - name: Build
      run: nimble build

    - name: List Files
      run: dir

    - name: Package
      run: |
        mv ./rangeit.exe ./rangeit-windows.exe
        mkdir -p release
        cp ./rangeit-windows.exe ./release/

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0
        release_name: Rangeit-Windows
        draft: false
        prerelease: false

    - name: Upload executable to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/rangeit-windows.exe
        asset_name: rangeit-windows.exe
        asset_content_type: application/octet-stream
