name: Build and Release for Windows

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Nim
      run: |
        curl https://nim-lang.org/choosenim/init.sh -sSf | sh -s -- -y
        export PATH=$HOME/.nimble/bin:$PATH

    - name: Build project
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        nimble build

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: rangeit-windows
        path: ./rangeit.exe
